spring:
  datasource:
    url: jdbc:postgresql://192.168.0.176:5432/aysw
    username: postgres
    password: mysecretpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    rest:
      default-page-size: 5
      max-page-size: 20

server:
  port: 8080

