spring:
  datasource:
    url: jdbc:postgresql://192.168.0.176:5432/aysw
    username: postgres
    password: mysecretpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

